function [BW,maskedImage] = lungSegmentationXY_graphcut(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 27-May-2019
%----------------------------------------------------


% Graph cut
foregroundInd = [70422 70424 70425 70426 70428 70429 70430 91326 176455 176456 177479 177846 179014 181572 183484 183617 186175 189126 189245 191802 192825 193747 194359 195892 196914 197345 198443 200484 201455 202013 203004 203015 203027 ];
backgroundInd = [95366 106633 112267 129679 135020 135529 135531 136036 137051 137056 138069 138574 139078 140603 141971 142127 143056 143063 143076 143081 143097 143110 143123 143133 143140 143552 145558 145559 145562 145569 145576 145585 ];
L = superpixels(X,1411);
BW = lazysnapping(X,L,foregroundInd,backgroundInd);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

