function [BW,maskedImage] = lungSegmentationXZ_graphcut(X)
%segmentImage Segment image using auto-generated code from imageSegmenter app
%  [BW,MASKEDIMAGE] = segmentImage(X) segments image X using auto-generated
%  code from the imageSegmenter app. The final segmentation is returned in
%  BW, and a masked image is returned in MASKEDIMAGE.

% Auto-generated by imageSegmenter app on 27-May-2019
%----------------------------------------------------


% Graph cut
foregroundInd = [76913 80498 85621 93820 94578 95090 96625 98161 99459 101230 103565 106643 106857 107671 108186 110238 111778 112483 112805 113318 113504 115037 115545 ];
backgroundInd = [42133 42162 42626 43735 44660 45309 49947 58158 66869 76085 85294 92453 93958 93959 93960 93963 93965 94992 94999 95001 95005 ];
L = superpixels(X,914);
BW = lazysnapping(X,L,foregroundInd,backgroundInd);

% Create masked image.
maskedImage = X;
maskedImage(~BW) = 0;
end

